### ISSUE TITLE
LOAD isn't working

### ISSUE THREAD

**Issue by rsbohn** [commanderx16/x16-emulator#162]
Pulled and built latest master d98151fa409ebddd2ddb842a2b07d0145db79c9a.
Pulled and build latest x16-rom 38f40b204555fa168b535dc05969b921b39e1d6e.

I can use -prg to load a program but the LOAD command isn't working.
Use the appended demo.bas to duplicate.

Expected results: Can LOAD a program that was just saved.

Actual results: Nothing is loaded. 

**$ cat demo.bas**
REM ./x16emu -bas demo.bas -echo
REM SHOW THAT THERE IS NO "DEMO" FILE
LOAD"$":LIST
NEW

REM ENTER A NEW PROGRAM
10 REM DEMO PROGRAM 2019.10.04
SAVE"DEMO":LIST

REM SHOW THAT "DEMO" IS SAVED
LOAD"$":LIST

NEW
REM LOADED "DEMO" BUT THERE IS NO PROGRAM
LOAD"DEMO":LIST

SYS$FFFF

**Comment by qbradq** [comment]
I reported this bug [here](https://github.com/commanderx16/x16-rom/issues/47) but thought it was a ROM issue. The -bas program line also does not seem to work.

**Comment by jjgignac** [comment]
It seems like this was my doing.  Revert commit f1e64161946 in the mean time if you need to get it working.  I'm working on the fix now.

**Comment by jjgignac** [comment]
It turns out that the bug was indeed in the BASIC ROM.  Due to an incorrect branch, the accumulator wasn't being restored after the call to parse the LOAD parameters.  As a result, the KERNAL (or the emulator override) was loading the data into video memory instead of normal RAM.  The bug would've shown up on real hardware too.  Should be fixed by https://github.com/commanderx16/x16-rom/pull/51.

**Comment by jjgignac** [comment]
Oh, as an aside, `LOAD"DEMO":LIST` (from your description) still won't work because the LOAD command prevents any command after the colon from executing.  This is expected long-standing behaviour.

**Comment by tonu1** [comment]
MAgB7RW6LudQ92QvSe19feGo7kYnBaWJd9
