### ISSUE TITLE
X16Emu doesn't run for Windows users with nonstandard names

### ISSUE THREAD

**Issue by Eleas** [commanderx16/x16-emulator#221]
In a fit of stupidity, I once decided my Windows username should be Björn. On running the exe, I get "Cannot open C:\Users\Bj├Ârn\Desktop\x16emu_win-r34\rom.bin!" and then back to prompt.

**Comment by mist64** [comment]
Weird. The path is returned by SDL_GetBasePath(), which returns a UTF-8 string. The file the gets opened using mingw's fopen(), which appears to be using the ANSI encoding.

We should use SDL_RWFromFile() instead of fopen().

**Comment by Serentty** [comment]
@mist64 On Windows, any standard library functions taking narrow strings are completely borked for modern usage because they use Windows codepages instead of UTF-8. These are misleadingly referred to as “ANSI”, but they're not a single encoding, and what “ANSI” actually is depends on the user's locale setting. It's a lot more complicated than the Unix world where normal narrow strings are usually just assumed to be UTF-8.

On Windows, unfortunately the only real solution is to convert the path from UTF-8 to UTF-16, and then pass it to functions which take wide strings, such as ``wfopen()``, as ``fopen()`` on Windows is essentially obsolete, despite being standard on Unix.

**Comment by Serentty** [comment]
And I stupidly missed that last part you wrote, where apparently SDL has functions for accessing a UTF-8 path. That seems simpler.

**Comment by Serentty** [comment]
@mist64 Okay, so I'm making progress on fixing file access (both filenames and reading the contents of BAS files) to use SDL's functions for UTF-8 on all platforms, but this has brought something else to my attention: the code uses ``printf()`` extensively for logging, which doesn't accept UTF-8 on Windows. This means that error messages containing filenames become garbled. It will probably be necessary to make a ``log()`` function which calls ``wprintf()`` on Windows and ``printf()`` on everything else to fix this. Is this something you could live with?

**Comment by Serentty** [comment]
Okay, so I've opened a pull request to switch file operations over, which should fix the most glaring issues.
