### ISSUE TITLE
Ctrl + S/V/R break with non-US keyboards

### ISSUE THREAD

**Issue by mist64** [commanderx16/x16-emulator#43]
Keyboard shortcuts use SDL_SCANCODE, which return the position, not the caption of the key.

**Comment by indigodarkwolf** [comment]
So in theory this just needs to replace the relevant control key checks against event.key.keysym.scancode with appropriate checks against event.key.keysym.sym? (Obviously only video.c lines 683-696, not the whole shebang.) 

I'll still need someone with a non-US keyboard layout to test a fix, I'm just asking here because there's no sense canvassing Facebook for volunteers if we already know my intended "fix" isn't sufficient.

**Comment by mist64** [comment]
I only read the first half of your comment, I'm sorry, so I merged a fix: 2fa42d5

I tested it by changing the keyboard layout on my Mac to French, and testing whether it hits the Cmd+A case I've added for testing (AZERTY vs. QWERTY).

I consider it fixed. :)
