### ISSUE TITLE
Request: Hook up SDL's Joystick interface to the x16 joystick interface

### ISSUE THREAD

**Issue by ElfEars** [commanderx16/x16-emulator#56]
I think testing joysticks would be much easier if we could use IRL joysticks, especially for two player. (Plus it would be a good feature in general, your arms get tired after a long day of typing!)

Obviously there would need to be some config file/command line magic to setup what type we're emulating (NES, Keyboard Cursors, SNES) and mapping IRL joystick buttons to virtual joystick buttons but otherwise SDL already comes with good cross platform joystick support.

**Comment by mist64** [comment]
For a start, I suggest the following command line options:
`-joy1 nes`
`-joy1 snes`
`-joy1 none`
`-joy2 nes`
`-joy2 snes`
`-joy2 none`
`none` would be the default for both. For now, we should just use a standard (non-configurable) mapping.

We should not map an SDL joystick to emulated keyboard keys, that would be  just  too confusing. Cursor keys and Ctrl, Alt, Space and Return are already detected by the system ROM as a fallback joystick 1 on both the emulator and on real hardware.

**Comment by mobluse** [comment]
I succeeded with connecting a cheap noname SNES USB gamepad to X16 in Raspbian Buster. First I had to name the window:
`xdotool search --onlyvisible --pid $(ps aux | grep x16emu | cut -c 9-15 | head -1) --name "\a\b\c" set_window --name 'X16 Emulator'`

Then I use the SNES as a NES keyboard joystick. The buttons that are not used send their button number in Linux (which starts at 0). The joystick has only 8 physical buttons, but sends 10.
`joy2key 'X16 Emulator' -X -dev /dev/input/js0 -buttons 0 1 Alt_L Control_L 4 5 6 7 space Return -axis Left Right Up Down -thresh -9 9 -9 9`

I cannot guarantee I got the A and B buttons right because I never had SNES och NES. SNES B = NES A, and SNES Y = NES B, if I understand correctly.

In Linux one can remap the buttons in the OS using jstest-gtk, or just jstest on the command line.

**Comment by jjbliss** [comment]
I'm looking into getting SDL Joysticks working on the emulator.  I've got some code writing to VIA that the kernal is picking up as joystick inputs.  I'll try to have something mostly working by tomorrow.

Does it matter for anything else where in the emulator loop I call into the controller code?  I haven't seen any problems yet, but there might a code order issue that I'm not aware of.

**Comment by tobier** [comment]
Shouldn't this be closed if a PR was merged?
